import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import MainLayout from '@/Layouts/MainLayout'
import { SiteIdContextProvider } from '@/context/SiteIdContextProvider'
import Head from 'next/head'
import GoogleTagManager from '@magicul/next-google-tag-manager';
//import {ServiceAppProvider} from '@/ContextAPI/compareData';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    
      <body className={inter.className}>
      <GoogleTagManager id="GTM-K3HFH7CF" />
        <SiteIdContextProvider>
         
            <MainLayout>
              {children}
            </MainLayout>
       
        </SiteIdContextProvider>
      
       
      </body>
    </html>
  )
}
